name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Choisissez l'environnement d'exécution (par exemple, Ubuntu)
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Choisissez la version de Java si nécessaire

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
